global using AutoRetainerAPI;
global using clib.Extensions;
global using ComplexTweaks.Attributes;
global using ComplexTweaks.Attributes.Config;
global using ComplexTweaks.IPC;
global using ComplexTweaks.Services;
global using ComplexTweaks.TweakSystem;
global using ComplexTweaks.Utilities;
global using ComplexTweaks.Utilities.Extensions;
global using Dalamud.Game.Addon.Lifecycle;
global using Dalamud.Game.Addon.Lifecycle.AddonArgTypes;
global using Dalamud.Game.ClientState.Conditions;
global using Dalamud.Interface.Utility;
global using Dalamud.Plugin.Services;
global using ECommons.GameHelpers;
global using ECommons.Logging;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Numerics;
global using static ComplexTweaks.Plugin;
global using static ComplexTweaks.Utilities.Enums;
global using static ECommons.GenericHelpers;
global using Callback = ECommons.Automation.Callback;
global using DGameObject = Dalamud.Game.ClientState.Objects.Types.IGameObject;
global using Sheets = Lumina.Excel.Sheets;
global using clib.TaskSystem;
global using clib.Services;
global using clib.Enums;
global using clib.Utils;
