using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;

namespace InteropSourceGenerators;

[Generator]
public class ServiceExtensionGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var serviceClassProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { Identifier.ValueText: "Service" },
                transform: static (ctx, _) => {
                    var serviceClass = (ClassDeclarationSyntax)ctx.Node;
                    var semanticModel = ctx.SemanticModel;
                    var serviceSymbol = semanticModel.GetDeclaredSymbol(serviceClass) as INamedTypeSymbol;
                    return (serviceClass, serviceSymbol);
                })
            .Where(static item => item.serviceSymbol != null)
            .Collect();

        context.RegisterSourceOutput(serviceClassProvider, GenerateExtensionMembers);
    }

    private static void GenerateExtensionMembers(SourceProductionContext context, ImmutableArray<(ClassDeclarationSyntax serviceClass, INamedTypeSymbol? serviceSymbol)> serviceClasses) {
        if (serviceClasses.IsDefaultOrEmpty)
            return;

        var (_, serviceSymbol) = serviceClasses[0];

        if (serviceSymbol == null)
            return;

        if (serviceSymbol.ContainingNamespace?.ToDisplayString() != "ComplexTweaks.Services")
            return;

        var properties = serviceSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.IsStatic && p.DeclaredAccessibility == Accessibility.Public)
            .OrderBy(p => p.Name)
            .ToList();

        if (properties.Count == 0)
            return;

        IndentedStringBuilder builder = new();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using clib.Services;");
        builder.AppendLine();
        builder.AppendLine("namespace ComplexTweaks.Services;");
        builder.AppendLine();

        using (builder.Block("public static class ServiceExtensions")) {
            using (builder.Block("extension(Svc)")) {
                foreach (var property in properties) {
                    var propertyType = property.Type.ToDisplayString(
                        new SymbolDisplayFormat(
                            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
                            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters));
                    var propertyName = property.Name;

                    builder.AppendLine($"public static {propertyType} {propertyName} => Service.{propertyName};");
                }
            }
        }

        context.AddSource("ServiceExtensions.g.cs", builder.ToString());
    }
}

