name: PR Builder for Plugins

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Store CWLSGoTo artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CWLSGoTo
        path: .\SamplePlugin\bin\x64\Release\CWLSGoTo\*
        if-no-files-found: error
        retention-days: 1

    - name: Store DesynthAllCommand artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DesynthAllCommand
        path: .\DesynthAllCommand\bin\x64\Release\DesynthAllCommand\*
        if-no-files-found: error
        retention-days: 1

    - name: Store LogoutOnTell artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LogoutOnTell
        path: .\LogoutOnTell\bin\x64\Release\LogoutOnTell\*
        if-no-files-found: error
        retention-days: 1

    - name: Store ModGuard artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ModGuard
        path: .\ModGuard\bin\x64\Release\ModGuard\*
        if-no-files-found: error
        retention-days: 1

    - name: Store TypoGuard artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TypoGuard
        path: .\TypoGuard\bin\x64\Release\TypoGuard\*
        if-no-files-found: error
        retention-days: 1

